/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.dto;

import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;

import java.util.List;

import javax.xml.bind.annotation.XmlRootElement;


@XmlRootElement
public abstract class _PacienteMasterDTO {

 
    protected PacienteDTO pacienteEntity;
    protected Long id;
    
    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }
    
    public PacienteDTO getPacienteEntity() {
        return pacienteEntity;
    }

    public void setPacienteEntity(PacienteDTO pacienteEntity) {
        this.pacienteEntity = pacienteEntity;
    }
    
    public List<ReporteDTO> createreporteDelPaciente;
    public List<ReporteDTO> updatereporteDelPaciente;
    public List<ReporteDTO> deletereporteDelPaciente;
    public List<ReporteDTO> listreporteDelPaciente;	
	
	
	
    public List<ReporteDTO> getCreatereporteDelPaciente(){ return createreporteDelPaciente; };
    public void setCreatereporteDelPaciente(List<ReporteDTO> createreporteDelPaciente){ this.createreporteDelPaciente=createreporteDelPaciente; };
    public List<ReporteDTO> getUpdatereporteDelPaciente(){ return updatereporteDelPaciente; };
    public void setUpdatereporteDelPaciente(List<ReporteDTO> updatereporteDelPaciente){ this.updatereporteDelPaciente=updatereporteDelPaciente; };
    public List<ReporteDTO> getDeletereporteDelPaciente(){ return deletereporteDelPaciente; };
    public void setDeletereporteDelPaciente(List<ReporteDTO> deletereporteDelPaciente){ this.deletereporteDelPaciente=deletereporteDelPaciente; };
    public List<ReporteDTO> getListreporteDelPaciente(){ return listreporteDelPaciente; };
    public void setListreporteDelPaciente(List<ReporteDTO> listreporteDelPaciente){ this.listreporteDelPaciente=listreporteDelPaciente; };	
	
	
}

