/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.master.persistence;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.persistence.entity.PacientereporteDelPacienteEntity;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.converter.ReporteConverter;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.dto.PacienteMasterDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.persistence.api._IPacienteMasterPersistence;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.api.IPacientePersistence;
import java.util.ArrayList;
import java.util.List;
import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

public class _PacienteMasterPersistence implements _IPacienteMasterPersistence {

  	@PersistenceContext(unitName="ClinicaKennedyPU")
 
    protected EntityManager entityManager;
    
    @Inject
    protected IPacientePersistence pacientePersistence;  

    public PacienteMasterDTO getPaciente(Long pacienteId) {
        PacienteMasterDTO pacienteMasterDTO = new PacienteMasterDTO();
        PacienteDTO paciente = pacientePersistence.getPaciente(pacienteId);
        pacienteMasterDTO.setPacienteEntity(paciente);
        pacienteMasterDTO.setListreporteDelPaciente(getPacientereporteDelPacienteEntityList(pacienteId));
        return pacienteMasterDTO;
    }

    public PacientereporteDelPacienteEntity createPacientereporteDelPacienteEntity(PacientereporteDelPacienteEntity entity) {
        entityManager.persist(entity);
        return entity;
    }

    public void deletePacientereporteDelPacienteEntity(Long pacienteId, Long reporteDelPacienteId) {
        Query q = entityManager.createNamedQuery("PacientereporteDelPacienteEntity.deletePacientereporteDelPacienteEntity");
        q.setParameter("pacienteId", pacienteId);
        q.setParameter("reporteDelPacienteId", reporteDelPacienteId);
        q.executeUpdate();
    }

    public List<ReporteDTO> getPacientereporteDelPacienteEntityList(Long pacienteId) {
        ArrayList<ReporteDTO> resp = new ArrayList<ReporteDTO>();
        Query q = entityManager.createNamedQuery("PacientereporteDelPacienteEntity.getByMasterId");
        q.setParameter("pacienteId",pacienteId);
        List<PacientereporteDelPacienteEntity> qResult =  q.getResultList();
        for (PacientereporteDelPacienteEntity entity : qResult) { 
            if(entity.getReporteDelPacienteIdEntity()==null){
                entityManager.refresh(entity);
            }
            resp.add(ReporteConverter.entity2PersistenceDTO(entity.getReporteDelPacienteIdEntity()));
        }
        return resp;
    }

}
