/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.entity.PacienteEntity;

public abstract class _PacienteConverter {

	public static PacienteDTO entity2PersistenceDTO(PacienteEntity entity){
		if (entity != null) {
			PacienteDTO dto = new PacienteDTO();
					dto.setAlturaMetros(entity.getAlturaMetros());
					dto.setEdad(entity.getEdad());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setPesoKg(entity.getPesoKg());
					dto.setDocumentoIdentificacion(entity.getDocumentoIdentificacion());
			return dto;
		}else{
			return null;
		}
	}
	
	public static PacienteEntity persistenceDTO2Entity(PacienteDTO dto){
		if(dto!=null){
			PacienteEntity entity=new PacienteEntity();
					entity.setAlturaMetros(dto.getAlturaMetros());
			
					entity.setEdad(dto.getEdad());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setPesoKg(dto.getPesoKg());
			
					entity.setDocumentoIdentificacion(dto.getDocumentoIdentificacion());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<PacienteDTO> entity2PersistenceDTOList(List<PacienteEntity> entities){
		List<PacienteDTO> dtos=new ArrayList<PacienteDTO>();
		for(PacienteEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<PacienteEntity> persistenceDTO2EntityList(List<PacienteDTO> dtos){
		List<PacienteEntity> entities=new ArrayList<PacienteEntity>();
		for(PacienteDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}