/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.doctor.master.persistence.entity;

import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.entity.PacienteEntity;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.entity.DoctorEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(DoctorpacienteDelDoctorEntityId.class)
@NamedQueries({
    @NamedQuery(name = "DoctorpacienteDelDoctorEntity.getByMasterId", query = "SELECT  u FROM DoctorpacienteDelDoctorEntity u WHERE u.doctorId=:doctorId"),
    @NamedQuery(name = "DoctorpacienteDelDoctorEntity.deleteDoctorpacienteDelDoctorEntity", query = "DELETE FROM DoctorpacienteDelDoctorEntity u WHERE u.doctorId=:doctorId and  u.pacienteDelDoctorId=:pacienteDelDoctorId")
})
public class DoctorpacienteDelDoctorEntity implements Serializable {

    @Id
    @Column(name = "doctorId")
    private Long doctorId;
    @Id
    @Column(name = "pacienteDelDoctorId")
    private Long pacienteDelDoctorId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "doctorId", referencedColumnName = "id")
    @JoinFetch
    private PacienteEntity doctorIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "pacienteDelDoctorId", referencedColumnName = "id")
    @JoinFetch
    private PacienteEntity pacienteDelDoctorIdEntity; 

    public DoctorpacienteDelDoctorEntity() {
    }

    public DoctorpacienteDelDoctorEntity(Long doctorId, Long pacienteDelDoctorId) {
        this.doctorId =doctorId;
        this.pacienteDelDoctorId = pacienteDelDoctorId;
    }

    public Long getDoctorId() {
        return doctorId;
    }

    public void setDoctorId(Long doctorId) {
        this.doctorId = doctorId;
    }

    public Long getPacienteDelDoctorId() {
        return pacienteDelDoctorId;
    }

    public void setPacienteDelDoctorId(Long pacienteDelDoctorId) {
        this.pacienteDelDoctorId = pacienteDelDoctorId;
    }

    public PacienteEntity getDoctorIdEntity() {
        return doctorIdEntity;
    }

    public void setDoctorIdEntity(PacienteEntity doctorIdEntity) {
        this.doctorIdEntity = doctorIdEntity;
    }

    public PacienteEntity getPacienteDelDoctorIdEntity() {
        return pacienteDelDoctorIdEntity;
    }

    public void setPacienteDelDoctorIdEntity(PacienteEntity pacienteDelDoctorIdEntity) {
        this.pacienteDelDoctorIdEntity = pacienteDelDoctorIdEntity;
    }

}
