/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReportePageDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.api._IReporteLogicService;

public abstract class _ReporteMockLogicService implements _IReporteLogicService {

	private Long id= new Long(1);
	protected List<ReporteDTO> data=new ArrayList<ReporteDTO>();

	public ReporteDTO createReporte(ReporteDTO reporte){
		id++;
		reporte.setId(id);
		data.add(reporte);
		return reporte;
    }
    
    public List<ReporteDTO> getReportes(){
		return data; 
	}

	public ReportePageDTO getReportes(Integer page, Integer maxRecords){
		ReportePageDTO response = new ReportePageDTO();
		response.setTotalRecords(Long.parseLong(data.size()+""));
		response.setRecords(data);
		return response;
	}

	public ReporteDTO getReporte(Long id){
		for(ReporteDTO data1:data){
			if(data1.getId().equals(id)){
				return data1;
			}
		}
		return null;
	}

	public void deleteReporte(Long id){
	    ReporteDTO delete=null;
		for(ReporteDTO data1:data){
			if(data1.getId().equals(id)){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
		} 
	}

	public void updateReporte(ReporteDTO reporte){
	    ReporteDTO delete=null;
		for(ReporteDTO data1:data){
			if(data1.getId().equals(reporte.getId())){
				delete=data1;
			}
		}
		if(delete!=null){
			data.remove(delete);
			data.add(reporte);
		} 
	}	
}