/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.converter;

import java.util.ArrayList;
import java.util.List;
import java.text.SimpleDateFormat;
import java.text.ParseException;
import java.util.logging.Level;
import java.util.logging.Logger;


import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.entity.ReporteEntity;

public abstract class _ReporteConverter {

 
	private final static SimpleDateFormat DATE_FORMAT = new SimpleDateFormat("dd/MM/yyyy");
	public static ReporteDTO entity2PersistenceDTO(ReporteEntity entity){
		if (entity != null) {
			ReporteDTO dto = new ReporteDTO();
					dto.setActividadFisica(entity.getActividadFisica());
					dto.setAlimentacion(entity.getAlimentacion());
 
			    if(entity.getFechaPublicacion() != null){
					dto.setFechaPublicacion(DATE_FORMAT.format(entity.getFechaPublicacion()));
				}	
					dto.setGravedad(entity.getGravedad());
					dto.setId(entity.getId());
					dto.setName(entity.getName());
					dto.setLocalizacionDolor(entity.getLocalizacionDolor());
					dto.setPatronDeSueno(entity.getPatronDeSueno());
			return dto;
		}else{
			return null;
		}
	}
	
	public static ReporteEntity persistenceDTO2Entity(ReporteDTO dto){
		if(dto!=null){
			ReporteEntity entity=new ReporteEntity();
					entity.setActividadFisica(dto.getActividadFisica());
			
					entity.setAlimentacion(dto.getAlimentacion());
			
 
			      try{ 
			        if(dto.getFechaPublicacion() != null){
						entity.setFechaPublicacion(DATE_FORMAT.parse(dto.getFechaPublicacion()));
					}
				  } catch (Exception ex) {
                        Logger.getLogger(_ReporteConverter.class.getName()).log(Level.SEVERE, null, ex);
                  }	
			
					entity.setGravedad(dto.getGravedad());
			
					entity.setId(dto.getId());
			
					entity.setName(dto.getName());
			
					entity.setLocalizacionDolor(dto.getLocalizacionDolor());
			
					entity.setPatronDeSueno(dto.getPatronDeSueno());
			
			return entity;
		}else {
			return null;
		}
	}
	
	public static List<ReporteDTO> entity2PersistenceDTOList(List<ReporteEntity> entities){
		List<ReporteDTO> dtos=new ArrayList<ReporteDTO>();
		for(ReporteEntity entity:entities){
			dtos.add(entity2PersistenceDTO(entity));
		}
		return dtos;
	}
	
	public static List<ReporteEntity> persistenceDTO2EntityList(List<ReporteDTO> dtos){
		List<ReporteEntity> entities=new ArrayList<ReporteEntity>();
		for(ReporteDTO dto:dtos){
			entities.add(persistenceDTO2Entity(dto));
		}
		return entities;
	}
}