/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.dto.DoctorDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.api.IDoctorLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.master.logic.api._IDoctorMasterLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.master.logic.dto.DoctorMasterDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.api.IPacienteLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import javax.inject.Inject;


public abstract class _DoctorMasterMockLogicService implements _IDoctorMasterLogicService {

    protected static ArrayList<DoctorMasterDTO> doctorMasterDtosList = new ArrayList<DoctorMasterDTO>() ;
    @Inject
    protected IPacienteLogicService pacientePersistance;
    @Inject
    protected IDoctorLogicService doctorPersistance;

    public DoctorMasterDTO createMasterDoctor(DoctorMasterDTO doctor) {

        doctorPersistance.createDoctor(doctor.getDoctorEntity());
        for (PacienteDTO dto : doctor.getCreatepacienteDelDoctor()) {
            doctor.getListpacienteDelDoctor().add(pacientePersistance.createPaciente(dto));
        }
        doctorMasterDtosList.add(doctor);
        return doctor;
    }

    public DoctorMasterDTO getMasterDoctor(Long id) {
        for (DoctorMasterDTO doctorMasterDTO : doctorMasterDtosList) {
            if (doctorMasterDTO.getDoctorEntity().getId() == id) {
                return doctorMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterDoctor(Long id) {
        for (DoctorMasterDTO doctorMasterDTO : doctorMasterDtosList) {
            if (doctorMasterDTO.getDoctorEntity().getId() == id) {

                for (PacienteDTO dto : doctorMasterDTO.getCreatepacienteDelDoctor()) {
                    pacientePersistance.deletePaciente(dto.getId());
                }
                doctorPersistance.deleteDoctor(doctorMasterDTO.getId());
                doctorMasterDtosList.remove(doctorMasterDTO);
            }
        }

    }

    public void updateMasterDoctor(DoctorMasterDTO doctor) {

		DoctorMasterDTO currentDoctor = getMasterDoctor(doctor.getDoctorEntity().getId());
		if (currentDoctor == null) {
			currentDoctor = doctor;
		}else{
			doctorMasterDtosList.remove(currentDoctor);
		}

        // update Paciente
        if (doctor.getUpdatepacienteDelDoctor() != null) {
            for (PacienteDTO dto : doctor.getUpdatepacienteDelDoctor()) {
                pacientePersistance.updatePaciente(dto);
                for (PacienteDTO pacientedto : currentDoctor.getListpacienteDelDoctor()) {
					if (pacientedto.getId() == dto.getId()) {
						currentDoctor.getListpacienteDelDoctor().remove(pacientedto);
						currentDoctor.getListpacienteDelDoctor().add(dto);
					}
				}
            }
        }
        // persist new Paciente
        if (doctor.getCreatepacienteDelDoctor() != null) {
            for (PacienteDTO dto : doctor.getCreatepacienteDelDoctor()) {
                PacienteDTO persistedPacienteDTO = pacientePersistance.createPaciente(dto);
                dto = persistedPacienteDTO;
                currentDoctor.getListpacienteDelDoctor().add(dto);
            }
        }
        // delete Paciente
        if (doctor.getDeletepacienteDelDoctor() != null) {
            for (PacienteDTO dto : doctor.getDeletepacienteDelDoctor()) {
				for (PacienteDTO pacientedto : currentDoctor.getListpacienteDelDoctor()) {
					if (pacientedto.getId() == dto.getId()) {
						currentDoctor.getListpacienteDelDoctor().remove(pacientedto);
					}
				}
                pacientePersistance.deletePaciente(dto.getId());
            }
        }
        doctorMasterDtosList.add(currentDoctor);
    }
}