/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.mock;
import java.util.ArrayList;
import java.util.List;

import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.api.IPacienteLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.api._IPacienteMasterLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.dto.PacienteMasterDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.api.IReporteLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import javax.inject.Inject;


public abstract class _PacienteMasterMockLogicService implements _IPacienteMasterLogicService {

    protected static ArrayList<PacienteMasterDTO> pacienteMasterDtosList = new ArrayList<PacienteMasterDTO>() ;
    @Inject
    protected IReporteLogicService reportePersistance;
    @Inject
    protected IPacienteLogicService pacientePersistance;

    public PacienteMasterDTO createMasterPaciente(PacienteMasterDTO paciente) {

        pacientePersistance.createPaciente(paciente.getPacienteEntity());
        for (ReporteDTO dto : paciente.getCreatereporteDelPaciente()) {
            paciente.getListreporteDelPaciente().add(reportePersistance.createReporte(dto));
        }
        pacienteMasterDtosList.add(paciente);
        return paciente;
    }

    public PacienteMasterDTO getMasterPaciente(Long id) {
        for (PacienteMasterDTO pacienteMasterDTO : pacienteMasterDtosList) {
            if (pacienteMasterDTO.getPacienteEntity().getId() == id) {
                return pacienteMasterDTO;
            }
        }

        return null;
    }

    public void deleteMasterPaciente(Long id) {
        for (PacienteMasterDTO pacienteMasterDTO : pacienteMasterDtosList) {
            if (pacienteMasterDTO.getPacienteEntity().getId() == id) {

                for (ReporteDTO dto : pacienteMasterDTO.getCreatereporteDelPaciente()) {
                    reportePersistance.deleteReporte(dto.getId());
                }
                pacientePersistance.deletePaciente(pacienteMasterDTO.getId());
                pacienteMasterDtosList.remove(pacienteMasterDTO);
            }
        }

    }

    public void updateMasterPaciente(PacienteMasterDTO paciente) {

		PacienteMasterDTO currentPaciente = getMasterPaciente(paciente.getPacienteEntity().getId());
		if (currentPaciente == null) {
			currentPaciente = paciente;
		}else{
			pacienteMasterDtosList.remove(currentPaciente);
		}

        // update Reporte
        if (paciente.getUpdatereporteDelPaciente() != null) {
            for (ReporteDTO dto : paciente.getUpdatereporteDelPaciente()) {
                reportePersistance.updateReporte(dto);
                for (ReporteDTO reportedto : currentPaciente.getListreporteDelPaciente()) {
					if (reportedto.getId() == dto.getId()) {
						currentPaciente.getListreporteDelPaciente().remove(reportedto);
						currentPaciente.getListreporteDelPaciente().add(dto);
					}
				}
            }
        }
        // persist new Reporte
        if (paciente.getCreatereporteDelPaciente() != null) {
            for (ReporteDTO dto : paciente.getCreatereporteDelPaciente()) {
                ReporteDTO persistedReporteDTO = reportePersistance.createReporte(dto);
                dto = persistedReporteDTO;
                currentPaciente.getListreporteDelPaciente().add(dto);
            }
        }
        // delete Reporte
        if (paciente.getDeletereporteDelPaciente() != null) {
            for (ReporteDTO dto : paciente.getDeletereporteDelPaciente()) {
				for (ReporteDTO reportedto : currentPaciente.getListreporteDelPaciente()) {
					if (reportedto.getId() == dto.getId()) {
						currentPaciente.getListreporteDelPaciente().remove(reportedto);
					}
				}
                reportePersistance.deleteReporte(dto.getId());
            }
        }
        pacienteMasterDtosList.add(currentPaciente);
    }
}