/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.ejb;

import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.api.IReportePersistence;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.api._IPacienteMasterLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.logic.dto.PacienteMasterDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.persistence.api.IPacienteMasterPersistence;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.master.persistence.entity.PacientereporteDelPacienteEntity;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.api.IPacientePersistence;
import javax.inject.Inject;

public abstract class _PacienteMasterLogicService implements _IPacienteMasterLogicService {

    @Inject
    protected IPacientePersistence pacientePersistance;
    @Inject
    protected IPacienteMasterPersistence pacienteMasterPersistance;
    @Inject
    protected IReportePersistence reportePersistance;

    public PacienteMasterDTO createMasterPaciente(PacienteMasterDTO paciente) {
        PacienteDTO persistedPacienteDTO = pacientePersistance.createPaciente(paciente.getPacienteEntity());
        if (paciente.getCreatereporteDelPaciente() != null) {
            for (ReporteDTO reporteDTO : paciente.getCreatereporteDelPaciente()) {
                ReporteDTO createdReporteDTO = reportePersistance.createReporte(reporteDTO);
                PacientereporteDelPacienteEntity pacienteReporteEntity = new PacientereporteDelPacienteEntity(persistedPacienteDTO.getId(), createdReporteDTO.getId());
                pacienteMasterPersistance.createPacientereporteDelPacienteEntity(pacienteReporteEntity);
            }
        }
        // update reporte
        if (paciente.getUpdatereporteDelPaciente() != null) {
            for (ReporteDTO reporteDTO : paciente.getUpdatereporteDelPaciente()) {
                reportePersistance.updateReporte(reporteDTO);
                PacientereporteDelPacienteEntity pacienteReporteEntity = new PacientereporteDelPacienteEntity(persistedPacienteDTO.getId(), reporteDTO.getId());
                pacienteMasterPersistance.createPacientereporteDelPacienteEntity(pacienteReporteEntity);
            }
        }
        return paciente;
    }

    public PacienteMasterDTO getMasterPaciente(Long id) {
        return pacienteMasterPersistance.getPaciente(id);
    }

    public void deleteMasterPaciente(Long id) {
        pacientePersistance.deletePaciente(id);
    }

    public void updateMasterPaciente(PacienteMasterDTO paciente) {
        pacientePersistance.updatePaciente(paciente.getPacienteEntity());

        //---- FOR RELATIONSHIP
        // persist new reporte
        if (paciente.getCreatereporteDelPaciente() != null) {
            for (ReporteDTO reporteDTO : paciente.getCreatereporteDelPaciente()) {
                ReporteDTO createdReporteDTO = reportePersistance.createReporte(reporteDTO);
                PacientereporteDelPacienteEntity pacienteReporteEntity = new PacientereporteDelPacienteEntity(paciente.getPacienteEntity().getId(), createdReporteDTO.getId());
                pacienteMasterPersistance.createPacientereporteDelPacienteEntity(pacienteReporteEntity);
            }
        }
        // update reporte
        if (paciente.getUpdatereporteDelPaciente() != null) {
            for (ReporteDTO reporteDTO : paciente.getUpdatereporteDelPaciente()) {
                reportePersistance.updateReporte(reporteDTO);
            }
        }
        // delete reporte
        if (paciente.getDeletereporteDelPaciente() != null) {
            for (ReporteDTO reporteDTO : paciente.getDeletereporteDelPaciente()) {
                pacienteMasterPersistance.deletePacientereporteDelPacienteEntity(paciente.getPacienteEntity().getId(), reporteDTO.getId());
                reportePersistance.deleteReporte(reporteDTO.getId());
            }
        }
    }
}
