/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.doctor.master.logic.ejb;

import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.api.IPacientePersistence;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.dto.DoctorDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.master.logic.api._IDoctorMasterLogicService;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.master.logic.dto.DoctorMasterDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.master.persistence.api.IDoctorMasterPersistence;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.master.persistence.entity.DoctorpacienteDelDoctorEntity;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.api.IDoctorPersistence;
import javax.inject.Inject;

public abstract class _DoctorMasterLogicService implements _IDoctorMasterLogicService {

    @Inject
    protected IDoctorPersistence doctorPersistance;
    @Inject
    protected IDoctorMasterPersistence doctorMasterPersistance;
    @Inject
    protected IPacientePersistence pacientePersistance;

    public DoctorMasterDTO createMasterDoctor(DoctorMasterDTO doctor) {
        DoctorDTO persistedDoctorDTO = doctorPersistance.createDoctor(doctor.getDoctorEntity());
        if (doctor.getCreatepacienteDelDoctor() != null) {
            for (PacienteDTO pacienteDTO : doctor.getCreatepacienteDelDoctor()) {
                PacienteDTO createdPacienteDTO = pacientePersistance.createPaciente(pacienteDTO);
                DoctorpacienteDelDoctorEntity doctorPacienteEntity = new DoctorpacienteDelDoctorEntity(persistedDoctorDTO.getId(), createdPacienteDTO.getId());
                doctorMasterPersistance.createDoctorpacienteDelDoctorEntity(doctorPacienteEntity);
            }
        }
        // update paciente
        if (doctor.getUpdatepacienteDelDoctor() != null) {
            for (PacienteDTO pacienteDTO : doctor.getUpdatepacienteDelDoctor()) {
                pacientePersistance.updatePaciente(pacienteDTO);
                DoctorpacienteDelDoctorEntity doctorPacienteEntity = new DoctorpacienteDelDoctorEntity(persistedDoctorDTO.getId(), pacienteDTO.getId());
                doctorMasterPersistance.createDoctorpacienteDelDoctorEntity(doctorPacienteEntity);
            }
        }
        return doctor;
    }

    public DoctorMasterDTO getMasterDoctor(Long id) {
        return doctorMasterPersistance.getDoctor(id);
    }

    public void deleteMasterDoctor(Long id) {
        doctorPersistance.deleteDoctor(id);
    }

    public void updateMasterDoctor(DoctorMasterDTO doctor) {
        doctorPersistance.updateDoctor(doctor.getDoctorEntity());

        //---- FOR RELATIONSHIP
        // delete paciente
        if (doctor.getDeletepacienteDelDoctor() != null) {
            for (PacienteDTO pacienteDTO : doctor.getDeletepacienteDelDoctor()) {
                doctorMasterPersistance.deleteDoctorpacienteDelDoctorEntity(doctor.getDoctorEntity().getId(), pacienteDTO.getId());
            }
        }
        // persist new paciente
        if (doctor.getCreatepacienteDelDoctor() != null) {
            for (PacienteDTO pacienteDTO : doctor.getCreatepacienteDelDoctor()) {
                DoctorpacienteDelDoctorEntity doctorPacienteEntity = new DoctorpacienteDelDoctorEntity(doctor.getDoctorEntity().getId(), pacienteDTO.getId());
                doctorMasterPersistance.createDoctorpacienteDelDoctorEntity(doctorPacienteEntity);
            }
        }
        // update paciente
        if (doctor.getUpdatepacienteDelDoctor() != null) {
            for (PacienteDTO pacienteDTO : doctor.getUpdatepacienteDelDoctor()) {
                doctorMasterPersistance.deleteDoctorpacienteDelDoctorEntity(doctor.getDoctorEntity().getId(), pacienteDTO.getId());
                pacientePersistance.updatePaciente(pacienteDTO);
                DoctorpacienteDelDoctorEntity doctorPacienteEntity = new DoctorpacienteDelDoctorEntity(doctor.getId(), pacienteDTO.getId());
                doctorMasterPersistance.createDoctorpacienteDelDoctorEntity(doctorPacienteEntity);
                
            }
        }
    }
}
