/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.dto.DoctorDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.dto.DoctorPageDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.api._IDoctorPersistence;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.converter.DoctorConverter;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.entity.DoctorEntity;

public abstract class _DoctorPersistence implements _IDoctorPersistence {

  	@PersistenceContext(unitName="ClinicaKennedyPU")
 
	protected EntityManager entityManager;
	
	public DoctorDTO createDoctor(DoctorDTO doctor) {
		DoctorEntity entity=DoctorConverter.persistenceDTO2Entity(doctor);
		entityManager.persist(entity);
		return DoctorConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<DoctorDTO> getDoctors() {
		Query q = entityManager.createQuery("select u from DoctorEntity u");
		return DoctorConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public DoctorPageDTO getDoctors(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from DoctorEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from DoctorEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		DoctorPageDTO response = new DoctorPageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(DoctorConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public DoctorDTO getDoctor(Long id) {
		return DoctorConverter.entity2PersistenceDTO(entityManager.find(DoctorEntity.class, id));
	}

	public void deleteDoctor(Long id) {
		DoctorEntity entity=entityManager.find(DoctorEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateDoctor(DoctorDTO detail) {
		DoctorEntity entity=entityManager.merge(DoctorConverter.persistenceDTO2Entity(detail));
		DoctorConverter.entity2PersistenceDTO(entity);
	}

}