/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReportePageDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.api._IReportePersistence;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.converter.ReporteConverter;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.entity.ReporteEntity;

public abstract class _ReportePersistence implements _IReportePersistence {

  	@PersistenceContext(unitName="ClinicaKennedyPU")
 
	protected EntityManager entityManager;
	
	public ReporteDTO createReporte(ReporteDTO reporte) {
		ReporteEntity entity=ReporteConverter.persistenceDTO2Entity(reporte);
		entityManager.persist(entity);
		return ReporteConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<ReporteDTO> getReportes() {
		Query q = entityManager.createQuery("select u from ReporteEntity u");
		return ReporteConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public ReportePageDTO getReportes(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from ReporteEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from ReporteEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		ReportePageDTO response = new ReportePageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(ReporteConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public ReporteDTO getReporte(Long id) {
		return ReporteConverter.entity2PersistenceDTO(entityManager.find(ReporteEntity.class, id));
	}

	public void deleteReporte(Long id) {
		ReporteEntity entity=entityManager.find(ReporteEntity.class, id);
		entityManager.remove(entity);
	}

	public void updateReporte(ReporteDTO detail) {
		ReporteEntity entity=entityManager.merge(ReporteConverter.persistenceDTO2Entity(detail));
		ReporteConverter.entity2PersistenceDTO(entity);
	}

}