/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.dto.DoctorPageDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.logic.dto.DoctorDTO;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.api.IDoctorPersistence;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.entity.DoctorEntity;
import co.edu.uniandes.csw.ClinicaKennedy.doctor.persistence.converter.DoctorConverter;
import static co.edu.uniandes.csw.ClinicaKennedy.util._TestUtil.*;

@RunWith(Arquillian.class)
public class DoctorPersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(DoctorPersistence.class.getPackage())
				.addPackage(DoctorEntity.class.getPackage())
				.addPackage(IDoctorPersistence.class.getPackage())
                .addPackage(DoctorDTO.class.getPackage())
                .addPackage(DoctorConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IDoctorPersistence doctorPersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from DoctorEntity").executeUpdate();
	}

	private List<DoctorEntity> data=new ArrayList<DoctorEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			DoctorEntity entity=new DoctorEntity();
			entity.setName(generateRandom(String.class));
			entity.setLogin(generateRandom(String.class));
			entity.setPassword(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createDoctorTest(){
		DoctorDTO dto=new DoctorDTO();
		dto.setName(generateRandom(String.class));
		dto.setLogin(generateRandom(String.class));
		dto.setPassword(generateRandom(String.class));
		
		DoctorDTO result=doctorPersistence.createDoctor(dto);
		
		Assert.assertNotNull(result);
		
		DoctorEntity entity=em.find(DoctorEntity.class, result.getId());
		
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getLogin(), entity.getLogin());
		Assert.assertEquals(dto.getPassword(), entity.getPassword());
	}
	
	@Test
	public void getDoctorsTest(){
		List<DoctorDTO> list=doctorPersistence.getDoctors();
		Assert.assertEquals(list.size(), data.size());
        for(DoctorDTO dto:list){
        	boolean found=false;
            for(DoctorEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getDoctorTest(){
		DoctorEntity entity=data.get(0);
		DoctorDTO dto=doctorPersistence.getDoctor(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getLogin(), dto.getLogin());
		Assert.assertEquals(entity.getPassword(), dto.getPassword());
        
	}
	
	@Test
	public void deleteDoctorTest(){
		DoctorEntity entity=data.get(0);
		doctorPersistence.deleteDoctor(entity.getId());
        DoctorEntity deleted=em.find(DoctorEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateDoctorTest(){
		DoctorEntity entity=data.get(0);
		
		DoctorDTO dto=new DoctorDTO();
		dto.setId(entity.getId());
		dto.setName(generateRandom(String.class));
		dto.setLogin(generateRandom(String.class));
		dto.setPassword(generateRandom(String.class));
		
		
		doctorPersistence.updateDoctor(dto);
		
		
		DoctorEntity resp=em.find(DoctorEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getLogin(), resp.getLogin());	
		Assert.assertEquals(dto.getPassword(), resp.getPassword());	
	}
	
	@Test
	public void getDoctorPaginationTest(){
		//Page 1
		DoctorPageDTO dto1=doctorPersistence.getDoctors(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        DoctorPageDTO dto2=doctorPersistence.getDoctors(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(DoctorDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(DoctorEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(DoctorDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(DoctorEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}