/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.master.persistence.entity;

import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.entity.ReporteEntity;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.entity.PacienteEntity;
import java.io.Serializable;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.IdClass;
import javax.persistence.ManyToOne;
import javax.persistence.NamedQueries;
import javax.persistence.NamedQuery;
import javax.persistence.PrimaryKeyJoinColumn; 
import org.eclipse.persistence.annotations.JoinFetch;

@Entity
@IdClass(PacientereporteDelPacienteEntityId.class)
@NamedQueries({
    @NamedQuery(name = "PacientereporteDelPacienteEntity.getByMasterId", query = "SELECT  u FROM PacientereporteDelPacienteEntity u WHERE u.pacienteId=:pacienteId"),
    @NamedQuery(name = "PacientereporteDelPacienteEntity.deletePacientereporteDelPacienteEntity", query = "DELETE FROM PacientereporteDelPacienteEntity u WHERE u.pacienteId=:pacienteId and  u.reporteDelPacienteId=:reporteDelPacienteId")
})
public class PacientereporteDelPacienteEntity implements Serializable {

    @Id
    @Column(name = "pacienteId")
    private Long pacienteId;
    @Id
    @Column(name = "reporteDelPacienteId")
    private Long reporteDelPacienteId;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "pacienteId", referencedColumnName = "id")
    @JoinFetch
    private ReporteEntity pacienteIdEntity;
    @ManyToOne
    @PrimaryKeyJoinColumn(name = "reporteDelPacienteId", referencedColumnName = "id")
    @JoinFetch
    private ReporteEntity reporteDelPacienteIdEntity; 

    public PacientereporteDelPacienteEntity() {
    }

    public PacientereporteDelPacienteEntity(Long pacienteId, Long reporteDelPacienteId) {
        this.pacienteId =pacienteId;
        this.reporteDelPacienteId = reporteDelPacienteId;
    }

    public Long getPacienteId() {
        return pacienteId;
    }

    public void setPacienteId(Long pacienteId) {
        this.pacienteId = pacienteId;
    }

    public Long getReporteDelPacienteId() {
        return reporteDelPacienteId;
    }

    public void setReporteDelPacienteId(Long reporteDelPacienteId) {
        this.reporteDelPacienteId = reporteDelPacienteId;
    }

    public ReporteEntity getPacienteIdEntity() {
        return pacienteIdEntity;
    }

    public void setPacienteIdEntity(ReporteEntity pacienteIdEntity) {
        this.pacienteIdEntity = pacienteIdEntity;
    }

    public ReporteEntity getReporteDelPacienteIdEntity() {
        return reporteDelPacienteIdEntity;
    }

    public void setReporteDelPacienteIdEntity(ReporteEntity reporteDelPacienteIdEntity) {
        this.reporteDelPacienteIdEntity = reporteDelPacienteIdEntity;
    }

}
