/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence;

import javax.inject.Inject;
import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.transaction.UserTransaction;

import org.jboss.arquillian.container.test.api.Deployment;
import org.jboss.arquillian.junit.Arquillian;
import org.jboss.shrinkwrap.api.ShrinkWrap;
import org.jboss.shrinkwrap.api.spec.WebArchive;
import org.junit.Assert;
import org.junit.Before;
import org.junit.Test;
import org.junit.runner.RunWith;
import java.util.*;


import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReportePageDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.logic.dto.ReporteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.api.IReportePersistence;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.entity.ReporteEntity;
import co.edu.uniandes.csw.ClinicaKennedy.reporte.persistence.converter.ReporteConverter;
import static co.edu.uniandes.csw.ClinicaKennedy.util._TestUtil.*;

@RunWith(Arquillian.class)
public class ReportePersistenceTest {

	public static final String DEPLOY = "Prueba";

	@Deployment
	public static WebArchive createDeployment() {
		return ShrinkWrap.create(WebArchive.class, DEPLOY + ".war")
				.addPackage(ReportePersistence.class.getPackage())
				.addPackage(ReporteEntity.class.getPackage())
				.addPackage(IReportePersistence.class.getPackage())
                .addPackage(ReporteDTO.class.getPackage())
                .addPackage(ReporteConverter.class.getPackage())
				.addAsResource("META-INF/persistence.xml", "META-INF/persistence.xml")
                .addAsWebInfResource("META-INF/beans.xml", "beans.xml");
	}

	@Inject
	private IReportePersistence reportePersistence;

	@PersistenceContext
	private EntityManager em;

	@Inject
	UserTransaction utx;

	@Before
	public void configTest() {
		System.out.println("em: " + em);
		try {
			utx.begin();
			clearData();
			insertData();
			utx.commit();
		} catch (Exception e) {
			e.printStackTrace();
			try {
				utx.rollback();
			} catch (Exception e1) {
				e1.printStackTrace();
			}
		}
	}

	private void clearData() {
		em.createQuery("delete from ReporteEntity").executeUpdate();
	}

	private List<ReporteEntity> data=new ArrayList<ReporteEntity>();

	private void insertData() {
		for(int i=0;i<3;i++){
			ReporteEntity entity=new ReporteEntity();
			entity.setActividadFisica(generateRandom(String.class));
			entity.setAlimentacion(generateRandom(String.class));
			entity.setFechaPublicacion(generateRandom(Date.class));
			entity.setGravedad(generateRandom(String.class));
			entity.setName(generateRandom(String.class));
			entity.setLocalizacionDolor(generateRandom(String.class));
			entity.setPatronDeSueno(generateRandom(String.class));
			em.persist(entity);
			data.add(entity);
		}
	}
	
	@Test
	public void createReporteTest(){
		ReporteDTO dto=new ReporteDTO();
		dto.setActividadFisica(generateRandom(String.class));
		dto.setAlimentacion(generateRandom(String.class));
dto.setFechaPublicacion(generateRandomDate());
		dto.setGravedad(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setLocalizacionDolor(generateRandom(String.class));
		dto.setPatronDeSueno(generateRandom(String.class));
		
		ReporteDTO result=reportePersistence.createReporte(dto);
		
		Assert.assertNotNull(result);
		
		ReporteEntity entity=em.find(ReporteEntity.class, result.getId());
		
		Assert.assertEquals(dto.getActividadFisica(), entity.getActividadFisica());
		Assert.assertEquals(dto.getAlimentacion(), entity.getAlimentacion());
Assert.assertEquals(parseDate(dto.getFechaPublicacion()), entity.getFechaPublicacion());	
		Assert.assertEquals(dto.getGravedad(), entity.getGravedad());
		Assert.assertEquals(dto.getName(), entity.getName());
		Assert.assertEquals(dto.getLocalizacionDolor(), entity.getLocalizacionDolor());
		Assert.assertEquals(dto.getPatronDeSueno(), entity.getPatronDeSueno());
	}
	
	@Test
	public void getReportesTest(){
		List<ReporteDTO> list=reportePersistence.getReportes();
		Assert.assertEquals(list.size(), data.size());
        for(ReporteDTO dto:list){
        	boolean found=false;
            for(ReporteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
	@Test
	public void getReporteTest(){
		ReporteEntity entity=data.get(0);
		ReporteDTO dto=reportePersistence.getReporte(entity.getId());
        Assert.assertNotNull(dto);
		Assert.assertEquals(entity.getActividadFisica(), dto.getActividadFisica());
		Assert.assertEquals(entity.getAlimentacion(), dto.getAlimentacion());
		Assert.assertEquals(entity.getGravedad(), dto.getGravedad());
		Assert.assertEquals(entity.getName(), dto.getName());
		Assert.assertEquals(entity.getLocalizacionDolor(), dto.getLocalizacionDolor());
		Assert.assertEquals(entity.getPatronDeSueno(), dto.getPatronDeSueno());
        
	}
	
	@Test
	public void deleteReporteTest(){
		ReporteEntity entity=data.get(0);
		reportePersistence.deleteReporte(entity.getId());
        ReporteEntity deleted=em.find(ReporteEntity.class, entity.getId());
        Assert.assertNull(deleted);
	}
	
	@Test
	public void updateReporteTest(){
		ReporteEntity entity=data.get(0);
		
		ReporteDTO dto=new ReporteDTO();
		dto.setId(entity.getId());
		dto.setActividadFisica(generateRandom(String.class));
		dto.setAlimentacion(generateRandom(String.class));
dto.setFechaPublicacion(generateRandomDate());
		dto.setGravedad(generateRandom(String.class));
		dto.setName(generateRandom(String.class));
		dto.setLocalizacionDolor(generateRandom(String.class));
		dto.setPatronDeSueno(generateRandom(String.class));
		
		
		reportePersistence.updateReporte(dto);
		
		
		ReporteEntity resp=em.find(ReporteEntity.class, entity.getId());
		
		Assert.assertEquals(dto.getActividadFisica(), resp.getActividadFisica());	
		Assert.assertEquals(dto.getAlimentacion(), resp.getAlimentacion());	
Assert.assertEquals(parseDate(dto.getFechaPublicacion()), resp.getFechaPublicacion());
		Assert.assertEquals(dto.getGravedad(), resp.getGravedad());	
		Assert.assertEquals(dto.getName(), resp.getName());	
		Assert.assertEquals(dto.getLocalizacionDolor(), resp.getLocalizacionDolor());	
		Assert.assertEquals(dto.getPatronDeSueno(), resp.getPatronDeSueno());	
	}
	
	@Test
	public void getReportePaginationTest(){
		//Page 1
		ReportePageDTO dto1=reportePersistence.getReportes(1,2);
        Assert.assertNotNull(dto1);
        Assert.assertEquals(dto1.getRecords().size(),2);
        Assert.assertEquals(dto1.getTotalRecords().longValue(),3L);
        //Page 2
        ReportePageDTO dto2=reportePersistence.getReportes(2,2);
        Assert.assertNotNull(dto2);
        Assert.assertEquals(dto2.getRecords().size(),1);
        Assert.assertEquals(dto2.getTotalRecords().longValue(),3L);
        
        for(ReporteDTO dto:dto1.getRecords()){
        	boolean found=false;	
            for(ReporteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
        
        for(ReporteDTO dto:dto2.getRecords()){
        	boolean found=false;
            for(ReporteEntity entity:data){
            	if(dto.getId().equals(entity.getId())){
                	found=true;
                }
            }
            Assert.assertTrue(found);
        }
	}
	
}