/* ========================================================================
 * Copyright 2014 ClinicaKennedy
 *
 * Licensed under the MIT, The MIT License (MIT)
 * Copyright (c) 2014 ClinicaKennedy

Permission is hereby granted, free of charge, to any person obtaining a copy
of this software and associated documentation files (the "Software"), to deal
in the Software without restriction, including without limitation the rights
to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
copies of the Software, and to permit persons to whom the Software is
furnished to do so, subject to the following conditions:

The above copyright notice and this permission notice shall be included in
all copies or substantial portions of the Software.

THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN
THE SOFTWARE.
 * ========================================================================


Source generated by CrudMaker version 1.0.0.201411201032

*/

package co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence;

import java.util.List;

import javax.persistence.EntityManager;
import javax.persistence.PersistenceContext;
import javax.persistence.Query;

import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacienteDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.logic.dto.PacientePageDTO;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.api._IPacientePersistence;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.converter.PacienteConverter;
import co.edu.uniandes.csw.ClinicaKennedy.paciente.persistence.entity.PacienteEntity;

public abstract class _PacientePersistence implements _IPacientePersistence {

  	@PersistenceContext(unitName="ClinicaKennedyPU")
 
	protected EntityManager entityManager;
	
	public PacienteDTO createPaciente(PacienteDTO paciente) {
		PacienteEntity entity=PacienteConverter.persistenceDTO2Entity(paciente);
		entityManager.persist(entity);
		return PacienteConverter.entity2PersistenceDTO(entity);
	}
	
	@SuppressWarnings("unchecked")
	public List<PacienteDTO> getPacientes() {
		Query q = entityManager.createQuery("select u from PacienteEntity u");
		return PacienteConverter.entity2PersistenceDTOList(q.getResultList());
	}

	@SuppressWarnings("unchecked")
	public PacientePageDTO getPacientes(Integer page, Integer maxRecords) {
		Query count = entityManager.createQuery("select count(u) from PacienteEntity u");
		Long regCount = 0L;
		regCount = Long.parseLong(count.getSingleResult().toString());
		Query q = entityManager.createQuery("select u from PacienteEntity u");
		if (page != null && maxRecords != null) {
		    q.setFirstResult((page-1)*maxRecords);
		    q.setMaxResults(maxRecords);
		}
		PacientePageDTO response = new PacientePageDTO();
		response.setTotalRecords(regCount);
		response.setRecords(PacienteConverter.entity2PersistenceDTOList(q.getResultList()));
		return response;
	}

	public PacienteDTO getPaciente(Long id) {
		return PacienteConverter.entity2PersistenceDTO(entityManager.find(PacienteEntity.class, id));
	}

	public void deletePaciente(Long id) {
		PacienteEntity entity=entityManager.find(PacienteEntity.class, id);
		entityManager.remove(entity);
	}

	public void updatePaciente(PacienteDTO detail) {
		PacienteEntity entity=entityManager.merge(PacienteConverter.persistenceDTO2Entity(detail));
		PacienteConverter.entity2PersistenceDTO(entity);
	}

}